### ISSUE TITLE
Esportazione RNDT compliant - Link esportazione

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#10]
GUI: Link per export XML

**Comment by taba90** [comment]
Sembra che non sia possibile aggiungere link di esportazione da schema-plugin, perché sono gestiti in un [Controller Angular ](https://github.com/geosolutions-it/core-geonetwork/blob/00a42edb69ef42333cb71d85d5aaabc02e058563/web-ui/src/main/resources/catalog/js/CatController.js#L177). Andrebbe quindi aggiunto su gn

**Comment by taba90** [comment]
La rappresentazione xml dei metadati rndt dovrebbe essere già compliant con le specifiche e non dovrebbe quindi essere necessario nessun link di esportazione ad hoc per metadati rndt.
