### ISSUE TITLE
Configurazione multi-IPA - Mappaggio IPA/gruppi

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#11]
Design e documentazione su come mappare uno o più IPA nei gruppi GN

**Comment by taba90** [comment]
- L'idea è quella di utilizzare il campo descrizione per definirvi l'IPA da recuperare in seguito tramite regex;

- Per concatenare l'IPA al file identifier sono da valutare due strade:
     1. tramite l'utilizzo di un  modello di identificatore dei metadati (Console di amministrazione -> metadati e modelli -> 
         Modelli di identificatori dei metadati) ipotesi ancora da valutare;
     2. tramite update-fixed-info.xsl, utilizzando al limite un procedura java invocabile da xsl; 

- Salvare l'IPA nella descrizione dei gruppi renderebbe inoltre quasi automatico il filtraggio degli IPA accessibili all'utente da scherma di editing del metadato (issue https://github.com/geosolutions-it/iso19139.rndt/issues/12).

**Comment by etj** [comment]
Preciso che l'idea è quella di mappare un solo codice IPA sul gruppo.
Non si esclude che più gruppi possano avere lo stesso iPA (ad esempio uffici diversi di uno stesso Ente).

@tdipisa confermi che questa soluzione è accettabile?

**Comment by tdipisa** [comment]
@etj confirmed.

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
Pull requests:

gn https://github.com/geosolutions-it/core-geonetwork/pull/27

note: il piano originale prevedeva l'utilizzo degli alias, ma non riuscivo a fare l'ovverride del bean, spring lanciava eccezzione per la presenza di bean con nome uguale. L'override si basa quindi su l'utilizzo dell'attributo primary true nei beans dei submoduli insieme al medesimo id.

Non c'è fork per la documentazione nella repo geosolutions. Io l'ho comunque aggiornata e pushata nella mia fork  https://github.com/taba90/doc/blob/update-schemaplugin-beans/source/customizing-application/implementing-a-schema-plugin.rst#customizing-spring-beans. Ho inserito l'aggiornamento nella sezione di creazione di uno schema plugin (immaginando che l'override dei bean serva per nuovi schema come nel caso nostro), ma forse va cambiata posizione.

rndt https://github.com/geosolutions-it/iso19139.rndt/pull/18
