### ISSUE TITLE
Errori nei thesauri

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139.rndt#116]
Quando si preme il bottone "choose keywords from thesaurus", la lista non dovrebbe mostrare i thesauri già usati nel metadato corrente

**Comment by etj** [comment]
Viene anche replicato il nome del thesaurus per ogni singola voce
![image](https://user-images.githubusercontent.com/717359/98040593-ceaa8300-1e20-11eb-94fb-1868b0c4c66c.png)

**Comment by etj** [comment]
Problema analogo con i thesauri fixed:
![image](https://user-images.githubusercontent.com/717359/98040782-2c3ecf80-1e21-11eb-9a02-87172e9ade4e.png)

**Comment by etj** [comment]
Nelle keyword free, compariva una label prima di ogni textbox, adesso no:
![image](https://user-images.githubusercontent.com/717359/98044764-abcf9d00-1e27-11eb-88ba-530cd7ac9463.png)

**Comment by taba90** [comment]
@etj non replico l'errore della duplicazione delle keywords. Ho avuto dei problemi solo con SpatialScope che in un'occasione ha rimostrato il bottone di aggiunta anche a keywords già presenti. Ho fatto una pr che fixa questo problema
