### ISSUE TITLE
Suggestions per interoperabilità

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#140]
Aggiunta suggestions per View Service e Download Service relativi al dataset (Plugin RNDT)

**Comment by taba90** [comment]
Dalla discussione con @etj: rispetto a quanto riportato sul documento che riportava il seguente link per la validazione esterna https://inspire-geoportal.ec.europa.eu/proxybrowser/#fq=memberStateCountryCode%3Ait&fq=sourceMetadataResourceLocator%3A%5C%2F*&fq=links%3Aerror.geoportal.discovery.metadata.xmlvalidation&fq=metadataPointOfContactOrgName_no_expansion%3A%22citt%C3%A0%20metropolitana%20di%20firenze%22&q=*%3A*, il portale INSPIRE sembra essere stato aggiornato, e non riportare più informazioni sull'indicatore di Interoperabilità quando viene richiesta la validazione esterna. L'issue perde dunque di significato.
