### ISSUE TITLE
Alcuni asterischi obbligatorietà mancano

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#165]
@tdipisa commented on [Tue Dec 01 2020](https://github.com/geosolutions-it/core-geonetwork/issues/63)

Sezione metadati comuni: Set dei caratteri dei metadati, Responsabile, Punto di contatto, Vincoli di accesso e fruibilità, localizzazione geografica. Sezione dataset e serie: Tema, Formato presentazione.

**Comment by tdipisa** [comment]
- 2.2.3 Set dei caratteri dei metdati [0..1]
- ""Contatto"" ha l'asterisco
- citedResponsibleParty da controllare 
- I vincoli di accesso sono una sottoclasse, non si può impostarne la cardianlità da XSD, ma ci sono regole schematorn che li controllano
- Estensione geografica controllata da schematron
- 3.2.1 formato di presentazione è [0..*]
- Tema da fixare

**Comment by taba90** [comment]
è possibile aggiungere gli asterischi di obbligatorietà da layout-custom-fields.xsl per gli accessConstraints.
1 ora
