### ISSUE TITLE
Aggiunta parole chiave da thesauri: problema non eliminabilità del box della ricerca sul thesaurus una volta caricato

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#166]
Campo/Tag: parole chiave da thesaurus
Sezione: metadati comuni/parole chiave (problema generale su tutti i template)

Se si aggiunge una buca di ricerca su uno specifico thesaurus anche se rimane vuota non c'è modo di eliminarla. Questo comportamento da problemi anche nella scheda in consultazione dove compare il thesaurus ma senza parole chiave associate.
Inoltre nel caso si usi un thesaurus di tipo gerarchico es. thesaurus dataset prioritari: il tool di selezione e navigazione dei valori non si riesce più a chiudere!

**Comment by taba90** [comment]
@etj il template xsl chiamato per il rendering delle keywords con thesauro è [questo]( https://github.com/geonetwork/core-geonetwork/blob/56ac6a12f5df06e194ed9f5a7bda521fbeeb8a56/web/src/main/webapp/xslt/ui-metadata/form-builder.xsl#L362
) dal [layout keywords di ISO19139](https://github.com/geonetwork/core-geonetwork/blob/56e55e9b69f1ecbbb0b0028fdf08a0415b77ca97/schemas/iso19139/src/main/plugin/iso19139/layout/layout-custom-fields-keywords.xsl#L140). Il template non gestisce l'aggiunta della delete. Andrebbe modificato e assicurarsi che la refDelete sia passata dal layout.xsl. Sembra necessario un intervento anche su gn. Altrimenti si può creare un xsl:template simile dentro il plugin rndt, copiando anche i layout-custom-fields-keywords.xsl da iso19139 a rndt per mantenere tutte le modifiche nel plugin. Stima 4-5 ore

**Comment by tdipisa** [comment]
Abbiamo concordato col cliente di non procedere su questo
