### ISSUE TITLE
Eliminazione Limitazioni d'uso nei template

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#167]
Sezione: metadati comuni/Vincoli sui dati ( problema generale su tutti i template)

Campo ormai opzionale (non lo istanziarei…) Lascerei solo la possibilità di aggiungerlo.

**Comment by tdipisa** [comment]
Eliminare dal template

**Comment by taba90** [comment]
vedi https://github.com/geosolutions-it/iso19139.rndt/issues/183
