### ISSUE TITLE
livello gerarchico

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#168]
Campo/tag: gmd:hierarchyLevel
Sezione: dataset e serie

Dovrebbe essere possibile inserirne uno solo non n. Per facilitare l'utente eliminerei la modifica ed eliminazione del campo. Dovrebbe essere un valore in lettura.

**Comment by tdipisa** [comment]
Fixare l'xsd
Non deve essere readonly: si deve poter switchare tra dataset e serie.

**Comment by taba90** [comment]
è già non eliminabile e non ci sono bottoni di aggiunta 
![livelloGerarchico](https://user-images.githubusercontent.com/46672505/100853433-0c361680-3488-11eb-9a61-83cc7dd1c40c.PNG)
