### ISSUE TITLE
Id_livello_superiore (dato)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#169]
Sezione: dataset e serie/Identificazione dati

Non dovrebbe essere possibile eliminarlo visto che è obbligatorio, anche perché quando lo si elimina in realtà nella vista full e quindi nell'xml permane. Una volta eliminato non c'è modo di farlo ricomparire nel template RNDT.

**Comment by tdipisa** [comment]
Si dovrebbe poter settare il livello superiore tramite pannello a dx ""risorse associate"" -> aggiungi -> collegamento al genitore.
- Ricontrollare
- Nell'update fixed info, se quel camponon esiste va creato ed impostato al valore di riorsa del metadato stesso.

**Comment by taba90** [comment]
Entrambe le funzionalità sono già implemente. Riguardo alla rimozione della delete è possibile, nella prospettiva di lasciare intatto l'xsd, non passare la refDelete al template xsl di rendering nel layout-custom-fields.xsl.   2 ore.

**Comment by etj** [comment]
L'xsl di eliminazione lascia l'elemento xml:
```
   <gmd:series>
      <gmd:CI_Series/>
   </gmd:series>
```
Nell'update-fixed-info i template che reimpostano l'id livello superiore hanno questi match:
```
  <xsl:template match="gmd:identificationInfo/*/gmd:citation/gmd:CI_Citation[not(gmd:series)]" >
```
e 
```
    <xsl:template match="gmd:series/gmd:CI_Series/gmd:issueIdentification"  priority="10">
```
per cui, una volta eliminato il parent, il valore di default non viene più riaggiunto.
