### ISSUE TITLE
Risorsa online

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#170]
Sezione: dataset e serie
Il blocco dovrebbe essere composto da i seguenti 4 tag: linkage, protocol,application profile e description.

**Comment by tdipisa** [comment]
Da ricontrollare

**Comment by taba90** [comment]
rimozione nome della risorsa e funzione. 1 ora. Riguardo alla funzione vedi https://github.com/geosolutions-it/iso19139.rndt/issues/171
