### ISSUE TITLE
Risorsa online/funzione

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#171]
Il campo non è richiesto nelle specifiche.

**Comment by tdipisa** [comment]
Eliminare campo funzione

**Comment by taba90** [comment]
è una raccomandazione per la risorsa on line dei servizi (Raccomandazione 3.4 pagina 91) rimuovo quindi solo da risorsa online dataset. 1 ora

**Comment by taba90** [comment]
rimosso campo funzione per dataset ma mantenuto per servizi (è nelle raccomandazioni) pr https://github.com/geosolutions-it/iso19139.rndt/pull/193
