### ISSUE TITLE
Classificazione dei servizi di dati territoriali

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#175]
- Tab comuni: evitare che venga mostrato il blocco keywords relativo a ""Classification of spatial data services""
- Tab servizi: fixare il rendering del thesaurus (ci sono campi esplosi)

**Comment by tdipisa** [comment]
- Tab comuni: evitare che venga mostrato il blocco keywords relativo a ""Classification of spatial data services""
- Tab servizi: fixare il rendering del thesaurus (ci sono campi esplosi)

**Comment by tdipisa** [comment]
Non è caricato il thesaurus relativo. Dovrebbe essere questo:  http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory

@etj da caricare il thesaurus mancante.

**Comment by etj** [comment]
L'installazione del thesaurus è già stata effettuata, come riportato nel doc di feedback.
Nella documentazione di configurazione era già presente.

@tdipisa è una issue nata già risolta?

**Comment by tdipisa** [comment]
@taba90 è necessaria una stima su questa issue

**Comment by taba90** [comment]
@etj @tdipisa riprodotto sul dev server è un problema riguardante il nome del thesauro per la classificazione dei servizi:

Da specifiche RNDT il titolo del thesauro  è "REGOLAMENTO (CE) N. 1205/2008 DELLA COMMISSIONE del 3 dicembre 2008 recante attuazione della direttiva 2007/2/CE del Parlamento europeo e del Consiglio per quanto riguarda i metadati"
anche se il thesauro è lo **spatialDataServiceCategory**.
Il titolo richiesto nelle specifiche è probabilmente un errore ma quando lo abbiamo rilevato decidemmo di lasciarlo così com'è annotando sulla documentazione il problema. Sul server è presente sì il thesauro ma senza il titolo modificato. Per questo non viene rilevato ed il blocco è esploso.
Avendo il title attualmente necessario, in locale non riproduco nessun errore:
![thesauroServizi](https://user-images.githubusercontent.com/46672505/101020277-86d96180-356e-11eb-9acc-830972d2caed.PNG)

Volendo posso cambiare il title per il detect del thesauro e non utilizzare quello probabilmente errato nelle specifiche. E' una modifica rapida < 1ora

**Comment by tdipisa** [comment]
@etj secondo quanto abbiamo discusso dobbiamo caricare il thesaurus mancante sul server.
