### ISSUE TITLE
Tipo di servizio

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#176]
Sezione: servizi

Ripulirei la combo dei suggerimenti e caricare i valori provenienti dal registro: https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType

**Comment by tdipisa** [comment]
Usare anche qui il rendering dei thesauri nei campi on keywork

**Comment by taba90** [comment]
3 ore
