### ISSUE TITLE
Associazione Risorsa accoppiata

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#177]
Sezione: servizi

Non c'è più possibilità di selezionare il metadato del dataset attraverso un tool di ricerca, scriverlo a mano non risulta tanto comodo e comunque porterebbe errori.
Inoltre serve che nell'xml il riferimento al metadato sia salvato come chiamata al CSW.
Esiste una relazione con il tool Risorse Associate del pannello di destra?

**Comment by tdipisa** [comment]
- Fixare il ""risorse associate""->aggiungi->""collegamento a un dataset""
- Dobbiamo rivedere la cosa

**Comment by taba90** [comment]
collegamento a dataset ha bisogno di un onlinesrc-add.xsl che manca nel plugin rndt. Si tratta di provare a utilizzare quello di iso19139 per vedere se funzione e nel caso riadattarlo. La stima è di **6 ore**

**Comment by taba90** [comment]
E' possibile creare la relazione tra dataset e servizio in due modi:

- da servizio verso dataset tramite opzione Collegamento a dataset: la risorsa accoppiata viene aggiornata nel metadato del servizio e la risorsa on-line viene aggiornata nel metadato del dataset. NB geonetwork permette l'operazione solo se lo url definito nella risorsa online è WMS.

- da dataset verso servizio tramite opzione Collegamento a service: la risorsa accoppiata del servizio viene aggiornata nel metadato del servizio e la risorsa on-line viene aggiornata nel metadato. Funziona con qualsiasi tipo di servizio.

- il popolamento automatico della risorsa on-line in entrambi i casi funziona parzialmente: da geonetwork i parametri passati al plugin sono parziali, per cui risulta correttamente popolato solo il campo url nel caso di link a servizio e campi url e protocol nel caso di link a risorsa (in questo secondo caso il popolamento è corretto perché viene forzata la selezione per i soli servizi WMS).
**Non  è un problema RNDT** ma la fuzionalità è stata implementata così per gn in generale, si vede provando gli stessi giri con iso19139. Se si vuole intervenire per fare un auto popolamento dell'elemento transferOptions completo è necessario modificare i js di geonetwork.
