### ISSUE TITLE
Aggiunta campo Nome richiesta

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#178]
Sezione: servizi/Operazioni

Manca come campo opzionale aggiungibile

**Comment by tdipisa** [comment]
Potrebbe essere un problema dell'XSD - ricontrollare

**Comment by taba90** [comment]
sembra essere un problema di template. Da editor l'element srv:operationName (nome richiesta) è gestito nell'add button.
è necessario aggiornare i template. Stima < 1 ora.
