### ISSUE TITLE
Modificare URL http://www.bipm.fr/en/si

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#180]
Campo/tag: accuratezza posizionale/gml:unitsSystem xlink:href
Sezione: dataset

Valore corretto: http://www.bipm.org/en/si

**Comment by tdipisa** [comment]
Da ricontrollare.

**Comment by taba90** [comment]
Si tratta di cambiare sostituire un valore, questione di minuti
