### ISSUE TITLE
Validazione: limitazioni d'uso

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#183]
Se rimosso viene segnalato errore sia per RNDT che per INSPIRE, ma non è più obbligatorio per RNDT. 
La struttura INSPIRE richiesta prevede un primo blocco `gmd:resourceConstraints` per documentare public access e un altro blocco di `gmd:resourceConstraints` per documentare insieme conditions for access and use. 
RNDT dovrebbe essersi adeguato rendendo opzionale il blocco `gmd:resourceConstraints/<gmd:MD_Constraints/<gmd:useLimitation>` che INSPIRE non ha mai previsto.

Questo il blocco obbligatorio per ISPIRE e RNDT:

```
<gmd:resourceConstraints>
	<gmd:MD_LegalConstraints>
		<gmd:accessConstraints>
			<gmd:MD_RestrictionCode codeList=""
                      				http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode""
                      				codeListValue=""
                      				otherRestrictions""/>
		</gmd:accessConstraints>
		<gmd:otherConstraints>
			<gmx:Anchor xlink:href=""
          				http://inspire.ec.europa.eu/metadatacodelist/LimitationsOnPublicAccess/noLimitations"">
				No limitations on public access
			</gmx:Anchor>
		</gmd:otherConstraints>
	</gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
<gmd:resourceConstraints>
	<gmd:MD_LegalConstraints>
		<gmd:useConstraints>
			<gmd:MD_RestrictionCode codeList=""
                      				http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode""
                      				codeListValue=""
                      				otherRestrictions""/>
		</gmd:useConstraints>
		<gmd:otherConstraints>
			<gmx:Anchor xlink:href=""
          				http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply"">
				No conditions apply to access and use
			</gmx:Anchor>
		</gmd:otherConstraints>
	</gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

**Comment by tdipisa** [comment]
Verificare

**Comment by taba90** [comment]
Unirei con issue https://github.com/geosolutions-it/iso19139.rndt/issues/167
- [ ] modificare rule schematron rndt per non controllare useLimitations;
- [ ] modificare template per rimuovere l'elemento useLimitations (?);
- [ ] eventualmente rimuovere da editor la gestione elemento useLimitations(?)
- [ ] testare che le schematron rule INSPIRE non falliscano in mancanza dell'elemento.

2 ore

**Comment by etj** [comment]
See also #209
