### ISSUE TITLE
MD_Identifier per Id risorsa 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#188]
Sezione: metadati comuni

Il tag da utilizzare è gmd:MD_Identifier non RS_Identifier.
La valorizzazione va fatta con URI risolvibile (da capire se quella che punta a RNDT o al CSW del catalogo locale, forse da chiarire con Rotundo)
Questa la struttura richiesta:

```
<gmd:identifier>            
   <gmd: MD_Identifier>    
      <gmd:code> <gco:CharacterString>https://geodati.gov.it/resource/id/r_piemon:00000001</gco:Cha racterString>
      </gmd:code>            
   </gmd:MD_Identifier>         
</gmd:identifier> 
```

**Comment by tdipisa** [comment]
- Il nome elemento MD_Identifier è una raccomandazione INSPIRE, ma RNDT usa indifferentemente entrambi (vedi Req RC.10). Cmq ok, da modificare.
- L'URI risolvibile è una raccomandazione, non il requisito
- Documentare la gestione dell'id risorsa

**Comment by taba90** [comment]
Sono necessarie modifiche nel cofig editor e nei templates. Il fix è rapido <= 1 ora
