### ISSUE TITLE
Review schermata di editing: fix vari

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/iso19139.rndt#19]
See https://docs.google.com/spreadsheets/d/1yQ0k_1eZ7e8HOoqDPrDunsSoamRcJApgKSlm4RC9Ccc/edit#gid=0

**Comment by taba90** [comment]
working on this

**Comment by etj** [comment]
- [x] Tab "Comuni: Rinominare in "Metadati comuni"
- [x] Sezione "Metadati": Rinominare in "Informazioni sui metadati" (§2.2)
- [x] Id file precedente: Togliere asterisco d'obbligatorietà (XSD?)
- [x] Sezione "Informazioni di identificazione": Rinominare in "Identificazione dei dati" (§2.3 pag 29)
- [x] Sistemi di riferimento: va spostato dal tab "Comuni" -> "dataset e serie"
- [x] Estensione temporale: va spostato da tab "dataset e serie" -> tab "comuni"

Dataset e serie:
- [x] Sezione "Metadati": Rinominare in "Informazioni sui metadati" 
- [x] Sezione "Informazioni di identificazione": Rinominare in "Identificazione dei dati" 
- [x] Informazioni supplementari: Spostare dopo categoria tematica
- [x] Distribuzione dei dati,  risorsa online, Frequenza:  Spostare dopo "sistemi di riferimento"
