### ISSUE TITLE
Validazione - Fix validazione GML

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#2]
Problemi di validazione di dataset probabilmente legata alla blocco estensione verticale. Questo l'errore:
Invalid content was found starting with element 'gml:GeodeticCRS'. One of '{""http://www.opengis.net/gml"":AbstractCRS}' is expected. (Element: gml:GeodeticCRS with parent element: gmd:verticalCRS)

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
Not reproducing the issue: validating the metadata from the editor did not report any error regarding CRS. Putting in a blocked state.

**Comment by taba90** [comment]
La validazione xsd presenta un bug generale su gn per il quale da un messaggio di successo validando sul singolo metadato (fallisce silenziosamente in realtà), mentre fallisce con messaggio di errore validando massivamente. 
Il fix per questo bug è nella pr https://github.com/geosolutions-it/core-geonetwork/pull/28

**Comment by etj** [comment]
Vedi #117
