### ISSUE TITLE
Risorsa online: refact pannello

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139.rndt#20]
Va completamente modificato il pannello, dato che molti campi adesso sono obbligatori

- `protocol`: obbligatorio, Anchor, da lista http://inspire.ec.europa.eu/metadata-codelist/ProtocolValue  
  - nota che alcuni dei valori raccomandati per protocol sono valori INTERNI che gn usa nella mappa per capire se una URL è una getCapa WMS. Vedi file web-ui/src/main/resources/catalog/views/default/config.js
- `applicationProfile`: obbligatorio, Anchor, da lista http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType
- `description`: obbligatorio, Anchor, valore fisso da http://inspire.ec.europa.eu/metadata-codelist/OnLineDescriptionCode

**Comment by etj** [comment]
![image](https://user-images.githubusercontent.com/717359/97003499-cb1f1e00-153b-11eb-95ac-dac38be16925.png)
Rimuovere URL e nilReason dalla visualizzazione.

Gli elementi Anchor di `protocol`, `applicationProfile` e `description` devono avere sia il testo che l'`href` relativi alla scelta effettuata, ad esempio:
```
<gmd:protocol>
   <gmx:Anchor xlink:href="http://www.opengis.net/def/serviceType/ogc/wfs">Web Feature Service (WFS)</gmx:Anchor>
</gmd:protocol>
```

**Comment by taba90** [comment]
rimetto in review e apro issue specifico per l'uso di thesauri per elementi diversi dalle keyword in modo da includere anche i constraints
