### ISSUE TITLE
CMFI - ulteriori specifiche al report di test

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#204]
Ulteriore riscontro del cliente come richiesto in relazione al [test report](https://docs.google.com/spreadsheets/d/12jNscj49Bz2gEozU1WY3gVqz_AIUZd3bmgzsRFSna9I/edit#gid=1865172677):

_"Come d'accordo allego 2 immagini relative alle vostre note "Dettagliare il problema" e "Quali suggerimenti? Se validazione, va rieseguita la validazione."_

- **I dati di ESTENSIONE GEOGRAFICA e  TEMPORALE non vengono correttamente visualizzati**
![vista_all_esteensione_temporale.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/b304019b-c2ca-4d6a-9a11-cb334264ea43)

- **VISTA ALL visualizza non correttamente dati sulla LONGITUDINE (E)**
![vista_all_longitudine_E.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/fd72163a-1bd7-401e-a1de-22ead1b1d3be)

- **I suggerimenti non si cancellano automaticamente al momento che si va a inserire il contenuto**
![suggerimenti_caselle_testo.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/08be42ad-ddee-4a86-95f7-3dcff8423c25)

**Comment by etj** [comment]
- Il problema relativo all'estensione geografica è dovuto al server WMS usato. Sarà fixato con l'upgrade a GN 3.10.6, ma intanto è stato committato un workaround con https://github.com/geosolutions-it/C024-CMF/issues/8
- È stato migliorato il layout nella "visualizzazione completa". Notare che comunque la data impostata non è validabile, in quanto "sconosciuto" è incompatibile quando impostato insieme ad un valore di data.
- Quello riferito come "testo suggerimento" in realtà è un contenuto vero e proprio del template (Si nota che non è un suggerimento anche dal colore stesso del testo).
