### ISSUE TITLE
Sistema di riferimento spaziale

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#213]
Campo: Sistema di riferimento spaziale
Sezione: dataset/serie

Il tag è compilato nel XML del template del dataset con un valore di default : WGS84;  ma il valore non compare sull'interfaccia. L'utente non ha percezione che è già presente un valore e tra l'altro che deve obbligatoriamente compilarlo (manca asterisco).

**Comment by etj** [comment]
Le specifiche riguardanti il sistema di riferimento (§3.5) non differenziano sintatticamente i sistemi di riferimento spaziale (qui come SRS) e i sistemi di riferimento temporale (SRT). Per questo motivo non è possibile né differenziarli nell’editor, né si possono verificarne i vincoli. Nello specifico l'elemento SRS ha cardinalità 1, SRT ha cardinalità 0..N. 

Non potendo distinguere un SRS da un SRT, non si potrà 
- indicare l’errore di mancanza di un SRS nel caso ci sia un solo SR, e questo sia in realtà un SRT. 
- indicare l’errore di SRS multipli, nel caso in cui siano presenti più SR, in quanto potrebbero essere tutti SRT
