### ISSUE TITLE
Check su validazione metadati

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#214]
Risultano presenti errori di validazione sui metadati harvestati. **I più rilevanti da controllare in questo momento sono i metadati harvestati da enti harvestati anche dall'hub centrale del cliente ODN.**

### Validazione da pagina di ricerca

Esempio di ricerca su [metadato](http://gn3-rndt.geo-solutions.it/geonetwork/srv/eng/catalog.search#/metadata/cmfi:1f4f933c-66df-4658-af44-803853272e12)):

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/a20eeed4-b538-410e-b2b0-4d170d62c8a9)

**Risultato validazione**
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/08eb84b2-26ff-41d3-a3ae-82c99cb51187)

### Validazione da pagina di modifica

Usando lo stesso [metadato](http://gn3-rndt.geo-solutions.it/geonetwork/srv/eng/catalog.search#/metadata/cmfi:1f4f933c-66df-4658-af44-803853272e12)) si ha un risultato differente rispetto alla validazione da pagina di ricerca.

**Risultato validazione**

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6c6fd35d-6829-4b6d-85ee-3adec64eba1f)

Da controllare anche altri metadati harvestati che interessano l'hub ODN.

**Comment by etj** [comment]
Ho nuovamente esportato il metadato dal catalogo ufficiale e reimportato in locale, e la validazione valida non ritorna errori.
Suppongo che il metadato possa essere stato editato sul server di staging.

**Comment by tdipisa** [comment]
@etj hai controllato anche altri metadati presenti come avevo scritto in descrizione? Quello che ho indicato era solo un esempio.

**Comment by tdipisa** [comment]
Chiusa in favore di #216, https://github.com/geosolutions-it/core-geonetwork/issues/15 e https://github.com/geosolutions-it/core-geonetwork/issues/22
