### ISSUE TITLE
Keyword - dataset prioritari, etc

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139.rndt#22]
In RNDT2.0 sono contemplate una serie di keyword opzionali basate su thesarus INSPIRE.
Vogliamo facilitare la lettura e l'inserimento di tali keyword. quindi la gestione di tali thesauri deve essere trasparente.
Prendiamo il caso di "parole chiavi per dataset prioritari".

- Nel caso in cui non esista ancora alcuna parola chiave con thesaurus "dataset proprietari":
  ![image](https://user-images.githubusercontent.com/717359/94788956-9ef8fd00-03d4-11eb-8be0-2052cca544a4.png)

- Una volta creata almeno una parola chiave:
  ![image](https://user-images.githubusercontent.com/717359/94789003-af10dc80-03d4-11eb-9cf4-9d56130686d2.png)

Quindi le modifiche necessarie sono:
- Label di struttura di primo livello: "Data set prioritari"
- "+ aggiungi parola chiave":  aggiungi dataset prioritario: viene aggiunto al metadato tutto un blocco `descriptiveKeywords`, con relative indicazioni del thesaurus
- "+" a blocco già esistente: aggiunge parola chiave all'interno del `descriptiveKeywords`
- "-" : rimuove parola chiave di dataset prioritario.
  Alla rimozione dell'ultima keyword, viene eliminato tutto il blocco descriptiveKeywords che contiene il thesaurus, e riapparirà il bottone "Aggiungi parola chiave per dataset prioritario"
- le info interne del thesaurus (titolo, data pubblicazione, etc) non vengono visualizzati, dato che abbiamo già la label di paragrafo che indica che stiamo trattando keyword per dataset prioritari

Tab "Metadati Comuni"
----------
 - impedire inserimento/visualizzazione/editing descriptiveKeyword delle keyword gestite nei tab serie/dataset e servizi
 - (2.3.6) gestire keyword libere (senza thesaurus)
 - gestire keyword con tesauri non gestiti dagli altri tab.

Tab serie/dataset
---------
In ordine:
   - (3.2.4.1) gestire keyword INSPIRE themes  
   - (3.2.4.2) gestire keyword dataset prioritari
   - (3.2.4.3) gestire keyword applicazioni territoriali
   - (3.2.4.4) gestire keyword opendata come semplice checkbox
   - (3.2.4.5) gestire keyword per dati interesse generale

Tab servizi
---------
   - (4.1.2.1) gestire keyword INSPIRE service types

**Comment by taba90** [comment]
- [x]  Label di primo livello -> thesaurusName;

- [x] + "thesaurusName" solo se elemento descriptiveKeywords per il thesaurus in questione non è già presente

- [x] Possibilità di aggiungere keyword se thesaurusName è già stato specificato;

- [x] delete progressivo sulle singole keywords, delete completo se keyword rimasta è solo una;

- [x] pulsante chooseKeywordFromThesaurus: blocked -> il pulsante viene visualizzato solo nella view full

**Comment by etj** [comment]
![image](https://user-images.githubusercontent.com/717359/96999776-09b1da00-1536-11eb-92d3-bd96d12acfbe.png)

- Il thesaurus dovrebbe essere preimpostato e non dovrebbe essere possibile modificarlo
- La URL del thesaurus non dovrebbe essere modificabile nè visualizzata (siamo nell'elemento "dataset prioritario", visualizzato come label di primo livello)
- il nilReason non dovrebbe essere impostabile/visualizzato

**Comment by etj** [comment]
Manca ancora la gestione di 
- gestire keyword per dati interesse generale
- gestire keyword opendata come semplice checkbox
