### ISSUE TITLE
Fix elementi MetadataStandard

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139.rndt#24]
`gmd:metadataStandardName` e `gmd:metadataStandardVersion` vanno definiti come:

    <gmd:metadataStandardName>
       <gco:CharacterString>Linee Guida RNDT</gco:CharacterString>
    </gmd:metadataStandardName>
    <gmd:metadataStandardVersion>
       <gco:CharacterString>2.0</gco:CharacterString>
    </gmd:metadataStandardVersion>

Questa modifica va impostata 
- su tutti i template
- nel file `schema-ident.xml`
- `schematron-rules-rndt.sch`
- `csw-full.xsl`
- `loc/ita/labels.xml`

Lo snippet nel file `schema-ident.xml` è usato per individuare a quale standard corrisponde un metadato appena importato.
La raccomandazione RC.4 raccomanda un `Anchor`, quindi 
il test dell'autodetect dovrebbe includere anche questo contenuto (da vedere come l'autodetect gestisce gli OR logici):
               
    <gmd:metadataStandardName>
        <gmx:Anchor xlink:href="https://registry.geodati.gov.it/document/lg-rndt">Linee Guida RNDT</gmx:Anchor>
    </gmd:metadataStandardName>

**Comment by taba90** [comment]
Geonetwork non supporta la possibilità di controllare possibili elementi multipli per lo stesso elemento parent con nel caso dell'elemento gmd:StandardName che può avere come children sia gco:CharacterString che gmx:Anchor.
In via provvisoria ho mantenuto il solo elemento gmd:StandardVersion in schema-ident.xml.
