### ISSUE TITLE
Revisione schermata di editing : fixes low priority

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/iso19139.rndt#27]
- [ ] campo lingua -> dropdwon con le solo lingue permesse req C.5

- [x] responsabile dei metadati -> Dovrebbe essere selezionabile dalla directory

- [x] nome del responsabile: manca il campo

- [x] responsabile dei dati -> Dovrebbe avere la stessa form del respopnsabile dei metadati

- [x] identificazione/data -> La dropdown di scelta tipo data non deve esserci: abbiamo solo data o data e orario, che è la prima scelta della dropdown

- [x] limitazioni d'uso -> Se rimosso, e non esistono sibling, dovrebbe essere rimosso tutto il blocco "vincoli della risorsa"

- [x]  Dataset/series livello gerarchico ->  mettere nella dropdown solo dataset e serie.
Si forniranno almeno un template per datase/serie e un template per servizi, quindi la scelta del livello base si effettuerà al'inizio, alla scelta del template.

- [x] formato di presentazione -> controllare che la lista visualizzata sia quella RNDT

- [x] otherDetails -> Dovrebbe essere textarea, non textfield

- [x] tipo rappr spaziale -> controllare che la lista visualizzata sia quella RNDT

- [x] dataset/series -> lingua livello sbagliato più controllare dropdown

- [x] tema -> Aggiungere a livello primario "Categoria tematica"

- [x] unità di misura -> non eliminabile sempre fissa a metro; snippet con solo value

- [x] Sistema di unità di misura -> ????

- [x] Coerenza topologica -> localizzare valori in dropdown

- [x] Sistema di riferimento spaziale e temporale ->aggiungere label giusta

- [x] abilitare nilReason per versione

- [x] formato di distribuzione Si potrebbe usare una dropdown con i valori di https://inspire.ec.europa.eu/media-types/
Racc R1.9 p77

- [x] frequenza -> controllare che la lista visualizzata sia quella RNDT

- [x] DCP -> Ha card [1..n], per cui deve essere possibile aggiungerne/rimoverle

- [x] standardName version + hierachyLevel e hierarcyLevelName (servizi) non editabili
- [ ] temporalElement dovrebbe essere possibili editare anche gli attributi indeterminate position

**Comment by tdipisa** [comment]
> identificazione/data -> La dropdown di scelta tipo data non deve esserci: abbiamo solo data o data e orario, che è la prima scelta della dropdown

@taba90, come suggerito da @etj possiamo forzare il formato atteso nell'update-fixed-info

**Comment by tdipisa** [comment]
Created #48 #49 for pending points in the description
