### ISSUE TITLE
Validazione - Fix validazione SRV

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#3]
La validazione del servizio presenta un errore sulla mancanza del formato

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
Not reproducing the issue. I found other problems with validation, mainly related to labels and loc/ita that I've fixed, but I need to check with @etj if we can't reproduce the client problem. I'm putting this temporarly in a blocked state.

**Comment by taba90** [comment]
issue reproduced putting back in progress state

**Comment by taba90** [comment]
pull request https://github.com/geosolutions-it/iso19139.rndt/pull/17
