### ISSUE TITLE
Visualizzazione metadato - Gestione parent

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#4]
Gestione per la visualizzazione di quanto implementato in task "Gestione codici"

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
dato che alcune modifiche erano cumulative sulla gestione del codice iPA ho aggiunto un commit in questa pr https://github.com/geosolutions-it/iso19139.rndt/pull/18/commits/746d5abb947483229cc9d6124471eddc7c21d372
