### ISSUE TITLE
Revisione schermata di editing: campo lingua

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#48]
Dropdwon con le solo lingue permesse req C.5
Da creare codelist

**Comment by etj** [comment]
@taba90 Controllare se è possibile rimuovere `xmlns:gml="http://www.opengis.net/gml"`, che tra l'altro è già definito nella root (con URI diversa)
```
   <gmd:language>
      <gmd:LanguageCode xmlns:gml="http://www.opengis.net/gml"
                        codeList="http://www.loc.gov/standards/iso639-2/"
                        codeListValue="fre">fre</gmd:LanguageCode>
   </gmd:language>
```

**Comment by etj** [comment]
Dovrebbe essere dovuto al diverso URI per `gml` nei vari xsl. 
Vedi #117
