### ISSUE TITLE
Revisione schermata di editing - Gestione IPa

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#5]
Possibilità di selezionare un codice IPA se non già assegnato

**Comment by taba90** [comment]
Visto il design corrente del mappaggio ipa/gruppi la issue perde quasi integralmente di significato:

- un ipa -> un gruppo;

- in fase di creazione del metadato l'utente seleziona un gruppo e quindi un ipa che è quindi unico;

- rimane come issue di studio per contrallare se esistono path particolari di creazione dei metadati  che richiedono una selezione dell'iPA

**Comment by etj** [comment]
Vanno gestiti i campi in tutti i path di creazione di un nuovo metadato:
- [x] Importazione dei metadati di esempio
- [x] Creazione di un metadato a partire da un metadato di esempio
- [x] Creazione di un metadato a partire da un template
- [x] Creazione di un metadato a partire da un metadato di catalogo
- [x] Creazione di un metadato come child di un metadato esistente
