### ISSUE TITLE
Revisione schermata di editing - Gestione codici

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/iso19139.rndt#7]
RNDT gestisce il versioning tramite parentIdentifier e la gerarchia metadata tramite i series
- Gestione codice precedente invio
- Gestione series

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
dato che alcune modifiche erano cumulative sulla gestione del codice iPA ho aggiunto un commit in questa pr https://github.com/geosolutions-it/iso19139.rndt/pull/18/commits/746d5abb947483229cc9d6124471eddc7c21d372
