### ISSUE TITLE
Servizi: keywords

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139.rndt#84]
Nascondere le info sul thesaurus, come fatto nel tab dataset/serie

![image.png](https://images.zenhubusercontent.com/5ce410b6d239f1194577a9b1/45045282-09f2-4a21-a427-07ef69cf2e27)

**Comment by etj** [comment]
Dopo la PR #104 mergiata:
![image](https://user-images.githubusercontent.com/717359/98037954-a91b7a80-1e1c-11eb-86e4-e493cbaa56a8.png)

**Comment by etj** [comment]
Questo thesaurus è presente
![image](https://user-images.githubusercontent.com/717359/98038868-1d0a5280-1e1e-11eb-93c2-09eb0c5f1cee.png)

**Comment by taba90** [comment]
[httpinspireeceuropaeumetadatacodelistSpatialDataServiceCategory-SpatialDataServiceCategory.zip](https://github.com/geosolutions-it/iso19139.rndt/files/5486419/httpinspireeceuropaeumetadatacodelistSpatialDataServiceCategory-SpatialDataServiceCategory.zip)
@etj  avevi ragione, il problema è con il nome del thesauro: da specifiche è diverso rispetto a quello INSPIRE. Prova usando questo con il name modificato

**Comment by etj** [comment]
Aggiunta documentazione:

Possibili errori riscontrati nella specifica
==========
§4.1.2.1 Identificazione dei servizi / Parole chiave
----------

È richiesto un thesaurus con titolo “REGOLAMENTO (CE) N. 1205/2008 DELLA COMMISSIONE del 3 dicembre 2008 recante attuazione della direttiva 2007/2/CE del Parlamento europeo e del Consiglio per quanto riguarda i metadati”.

Il titolo del thesaurus ufficiale INSPIRE è “Classificazione dei servizi di dati territoriali”, è questo è l’unico caso in cui viene richiesto un titolo diverso da quello ufficiale.

Il titolo include “per quanto riguarda i metadati”, mentre il thesaurus è esplicitamente un insieme di voci riguardanti i servizi.

Il titolo sembra più il testo di una specifica di conformità che non un titolo di thesaurus, per cui può trattarsi di un copiaincolla nell’elemento sbagliato.
