### ISSUE TITLE
Servizi: elemento "Operazione"

### ISSUE THREAD

**Issue by etj** [geosolutions-it/iso19139.rndt#87]
Il pannello ha troppi elementi:
![image.png](https://images.zenhubusercontent.com/5ce410b6d239f1194577a9b1/400ca6a0-8779-4932-8344-08aa7b8224ca)

Sono richiesti:
- nome operazione [1] ok
- DCP [1..n] ok
- nome richiesta [0..1] ok
- punto di connessione [1..n]  - da fixare
  pdc va espresso solo con la URL dell'endpoint, nel formato

      <gmd:CI_OnlineResource>
         <gmd:linkage>
            <gmd:URL/>
               </gmd:linkage>http://etc

**Comment by tdipisa** [comment]
@etj please check it again. @taba90 cannot reproduce this.

**Comment by etj** [comment]
Non riesco più a replicarla nemmeno io. Chiudo.
